server:
  port: 8082

mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 33306
  dbName: shopgo
  maxIdleConns: 10 # số lượng idle connect tối đa
  maxOpenConns: 100
  connMaxLifetime: 3600 # vòng đời tối đa của một connect

logger:
  log_level: debug
  file_log_name: "./storages/dev/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
