server:
  port: 8082
  mode: "dev"

mysql:
  user: root
  # password: 12345678
  password: root
  host: 127.0.0.1
  port: 3306
  dbName: shopdev
  maxIdleConns: 10 # số lượng idle connect tối đa
  maxOpenConns: 100
  connMaxLifetime: 3600 # vòng đời tối đa của một connect

logger:
  log_level: debug
  file_log_name: "./storages/dev/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
